sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: 3uV4iXpxDp82Libe0HlzhC9SyMaK/ZtAcZXOI3ZTaYVw8x3tBjrH4Bk2bIvaovFDafs5bz3w+udZmWGuO9lq70DrQfrFAmgNaR23CwS5XVoyd/gTf2oFkQxZQwlZRKFoFVpx7OnOChF4B+kv8NM2Yw6QtoWigA+jFEa5YkSSrxN/p5mzcyYPB969ZBhcpEUqob/JEci49rNcIte/1UwwaYjHF8Z6Iu3y6lBmkfQ3S44zn//0VUiC6ZOwSv1SwKqlgby1PwcuDlQi+Mc9BtxXQsrXHGyO4oJ0va5oGsH+F9Z3pofIL//Sq/sJ0+n/6JV80Y6jpEQ4oDdbNukN5NKHhMlGKC+oXM0gn9N+gcwGaZIj436JoGUrxY8cBr6Vggl9OrxBUmReeeVa8qRH/9o+MspIPInvl3iEfNgC2Ny0JRyUNQBuPGtYYvk4qKFlyvJyuw/gKgjXRXYaslLiyGkYAtlcvNLSLMxEhbUZh2ZO+JuB2/gr6PQYdrKiNmTY3zXsd8wZj/FONSEz9zWvMTkAwGeX5rHmP/4cL9wgzVHW8IrPFIBJYZ/U1XLabHZINs+q2lXpq2UBDcdQmTHSMs7mHw1Rdd8+vyb9XhrEaw6TuJPuH9bIwoO1HlIH+G10napgWGe1Fwh4kOLo7ojXomZEA3jJMhKjcGzZepYNqvgdfPc=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/The-Glimpses-of-the-Moon_1263
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy